### ISSUE TITLE
Dependencies should be retrieved when starting a new session

### ISSUE THREAD

**Issue by ilanbiala** [alanshaw/david-www#178]
I'm not sure how often dependencies are retrieved, but it seems like the cache on the website is very long. Is it possible to check if the date modified on `package.json` is more recent than when David last generated the table?

**Comment by alanshaw** [comment]
There's two caches in david-dm.org:

Firstly, your package.json file is cached for an hour to ensure david keeps within the github rate limits. We could lower this if we leverage [conditional requests](https://developer.github.com/v3/#conditional-requests). I'd be really happy to accept a pull request that adds this!

Note that when you publish to npm, david will automatically [expire any cached package.json](https://github.com/alanshaw/david-www/blob/master/manifest.js#L173-L188) if the project has included repo info.

Secondly, version information for each package in npm is [cached for ages](https://github.com/alanshaw/david-www/blob/master/config/default.json#L3), but because david is listening for npm registry changes, [cached version information is expired](https://github.com/alanshaw/david-www/blob/master/brains.js#L14) when publishes occur.

**Comment by alanshaw** [comment]
I've just published a new version of a package and it looks as though david isn't currently expiring the cached package.json for the project - will investigate

**Comment by satazor** [comment]
@alanshaw I'm still getting the same issue as the OP stated. I'm publishing new versions and DM takes way too long to update them. I don't think your commit actually fixed the issue. :(

**Comment by alanshaw** [comment]
Thanks for the heads up @satazor - would you be willing to look into the problem and submit a patch?

**Comment by satazor** [comment]
Yes I think I can take a look at that. Could you point me the part of the project where the "update" hook gets performed?

**Comment by alanshaw** [comment]
I think you need to look here: https://github.com/alanshaw/david-www/blob/master/lib/manifest.js#L191
